#!/bin/bash

# First build with all combinations of features to check for doc
# issues (bad links etc, e.g. especially references to QCellOwner from
# no_std docs).  Then finally build as docs.rs sees it to visually
# check the "std" and "alloc" annotations on some types.

./run-feature-combinations |
    while read msrv features
    do
        echo "=== Features: $features"
        cargo doc --no-default-features --features "$features" || exit 1
    done

echo "=== Docs.rs output"
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
