#!/bin/bash

./run-feature-combinations |
    while read msrv features
    do
        echo "=== Features: $features"
        cargo test --no-default-features --features "$features" || exit 1
    done

echo SUCCESS
